# Memento Numpy 

Le langage de programmation *Python* sera présenté en détail dans le cadre de l'UE animée par Christophe Guicheney. Ci-dessous :  
* sont rappelées quelques instructions de base de ce langage
* et présentées les instructions du package *Numpy* utiles pour réaliser ce TD

La prise en main du package Matplotlib est présentée dans chaque Notebook, sur la partie chargement des données  
*(pour réaliser un tracé en trait continu plutôt que point par point, on remplace* plt.scatter *par* plt.plot*)*

## Boucles 
1) l'instruction qui définit la boucle doit se terminer par le caractère *deux-points*  
2) tout ce qui est dans la boucle doit être indenté  
3) et dès qu'on met fin à l'indentation, on sort de la boucle, cela dispense d'une instruction *end*  
4) la fonction *range(n)* crée une liste qui part de *0*, s'incrémente de *1* et se termine à *n-1* 

In [1]:
for i in range(3):
    print(i)
print('on est sorti de la boucle')

0
1
2
on est sorti de la boucle


In [2]:
x = 10
if x < 0:
    print('la valeur de x est strictement négative, précisément on a x = ',x)
elif x > 0:
    print('la valeur de x est strictement positive, précisément on a x = ',x)
else: 
    print('la valeur de x est nulle')
print('on est sorti de la boucle')

la valeur de x est strictement positive, précisément on a x =  10
on est sorti de la boucle


In [3]:
x = 0
while x < 3:
    x += 1
print('au final, la valeur de x est : ',x)

au final, la valeur de x est :  3


## Fonctions 
1) les fonctions sont définies par le mot-clé *def*, suivi du nom de la fonction, des paramètres d'entrée entre parenthèses, et enfin du caractère *deux-points*  
2) tout ce qui est dans la fonction doit être indenté  
3) si on veut retourner des variables, il faut les faire précéder de l'instruction *return*  
4) et dès qu'on met fin à l'indentation, on sort de la fonction, cela dispense d'une instruction *end*  

In [4]:
def SommeProduit(a,b):
    somme = a+b
    produit = a*b
    return somme, produit

In [5]:
s,p = SommeProduit(2,3)
print('La somme des 2 nombres est : ',s)
print('Le produit des 2 nombres est : ',p)

La somme des 2 nombres est :  5
Le produit des 2 nombres est :  6


## Affichage

Si on veut afficher les nombres flottant en limitant à 4 décimales, on peut précéder ainsi

In [6]:
a = 1/3
print('La valeur contenue dans a est : ',a)
print('La valeur contenue dans a est {:.4f}'.format(a))
print('La valeur contenue dans a est {:.4e}'.format(a))

La valeur contenue dans a est :  0.3333333333333333
La valeur contenue dans a est 0.3333
La valeur contenue dans a est 3.3333e-01


## Numpy

In [4]:
import numpy as np

Le package *numpy* propose quelques fonctions prédéfinies :  
* **np.sqrt()**
* **np.cos()**
* **np.sin()**
* **np.arctan()**
* **np.norm()**

ainsi que la valeur du nombre $\pi$ : **np.pi**

## Saisie de matrices  
La saisie d'une matrice $3\times3$ peut être réalisée en utilisant 3 jeux de crochets séparés par des virgules au sein d'un crochet principal dans l'instruction *np.array*  
Sa dimension peut être obtenue via l'attribut *shape*

In [6]:
A = np.array( [ [1,2,3] , [4,5,6] , [7,8,9] ] )
print('matrice A')
print(A)
print('Shape de A :',A.shape)

matrice A
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape de A : (3, 3)


On accède à un élément d'une matrice en exploitant les crochets  
La première ligne ou la première colonne porte **l'index 0**

In [7]:
print('L\'élément ligne 1 colonne 1 est ',A[0,0])
print('L\'élément ligne 3 colonne 3 est ',A[2,2])

L'élément ligne 1 colonne 1 est  1
L'élément ligne 3 colonne 3 est  9


Le caractère *deux-points* permet de spécifier une plage : le champ **début : fin** désigne une plage qui commence à l'indice ***début*** et s'arrête à l'indice ***fin - 1*** 

Le caractère *deux-points* tout seul indique que l'on prend toute la ligne ou colonne

In [10]:
print('Les éléments des 2 premières lignes et 2 dernières colonnes sont :')
print(A[0:2,1:3])

Les éléments des 2 premières lignes et 2 dernières colonnes sont :
[[2 3]
 [5 6]]


In [11]:
print('Les éléments des 2 dernières colonnes sont :')
print(A[:,1:3])

Les éléments des 2 dernières colonnes sont :
[[2 3]
 [5 6]
 [8 9]]


In [12]:
print('Les éléments de la dernière colonne sont :')
print(A[:,2])

Les éléments de la dernière colonne sont :
[3 6 9]


Si on définit un vecteur, alors on n\'utilise que le crochet principal  
Il n'est ni ligne ni colonne, sa 2nde dimension est indéfinie, comme indiqué par sa shape

In [13]:
V = np.array( [ 1,2,3 ] )
print('Le vecteur V n\'est ni ligne ni colonne : ',V)
print('Cela est souligné par sa shape : ',V.shape)

Le vecteur V n'est ni ligne ni colonne :  [1 2 3]
Cela est souligné par sa shape :  (3,)


Comme le vecteur n'est ni ligne ni colonne, un seul indice suffit pour isoler des élements  
L'index **-1** désigne le dernier élément

In [14]:
print('Les 2 derniers éléments de V sont : ',V[1:3])
print('Le dernier élément de V est : ',V[-1])

Les 2 derniers éléments de V sont :  [2 3]
Le dernier élément de V est :  3


Si pour assembler des matrices on a besoin de forcer le vecteur à être colonne ou ligne, alors on utilise la méthode **reshape**

In [15]:
print('Pour créer un vecteur colonne : ')
Vc = V.reshape(-1,1)
print(Vc)
print('Sa shape est désormais ',Vc.shape)

Pour créer un vecteur colonne : 
[[1]
 [2]
 [3]]
Sa shape est désormais  (3, 1)


In [16]:
print('Pour créer un vecteur ligne : ')
Vl = V.reshape(1,-1)
print(Vl)
print('Sa shape est désormais ',Vl.shape)

Pour créer un vecteur ligne : 
[[1 2 3]]
Sa shape est désormais  (1, 3)


Mais dans ce cas, il faut 2 indices pour accéder à un élément  

In [17]:
print('Le second élément de Vl est : ',Vl[0,1])

Le second élément de Vl est :  2


In [18]:
print('Les deux derniers éléments de Vc sont : ',Vc[1:3:,0])

Les deux derniers éléments de Vc sont :  [2 3]


La longueur et la somme des éléments d'un vecteur s'obtiennent comme suit :

In [19]:
print('La longueur de V est :',len(V))
print('La somme des éléments de V est : ',sum(V))

La longueur de V est : 3
La somme des éléments de V est :  6


## Matrices classiques  
Pour créer des matrices de zéros ou de uns, on utilise ***np.zeros*** et ***np.ones***, avec les dimensions données **entre parenthèses** au sein **des parenthèses** associées à la fonction

In [20]:
z = np.zeros((2,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
u = np.ones((3,2))
print(u)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Enfin, ***np.linspace(début,fin,nb)*** permet de générer un vecteur de ***nb*** éléments équi-répartis entre ***début*** et ***fin***

In [13]:
x = np.linspace(2,12,6)
print(x)

[ 2.  4.  6.  8. 10. 12.]


## Opérations sur les matrices

In [22]:
A = np.array( [ [1,2,0] , [3,0,4] , [0,5,6] ] )
B = np.array( [ [1,2] , [3,4] , [5,6] ] )
print('Voici la matrice A')
print(A)
print('Voici la matrice B')
print(B,'\n')

print('On obtient ainsi la transposée de B : ')
print(B.T,'\n')

print('Par défaut, toute opération sur les matrices est réalisée terme à terme')
print('Pour faire un produit matriciel, on utilise la méthode .dot()')
print(A.dot(B),'\n')

print('L\'inverse d\'une matrice carrée s\'obtient comme suit. inv(A) est :')
print(np.linalg.inv(A),'\n')

print('La pseudo-inverse d\'une matrice rectangulaire s\'obtient comme suit. pinv(B) est :')
print(np.linalg.pinv(B),'\n')

print('Pour concaténer deux matrices horizontalement, on utilise l\'instruction np.hstack,')
print('en plaçant les matrices entre parenthèses au sein des parenthèses de la fonction hstack :')
print(np.hstack( ( A , B )),'\n')

print('Pour concaténer deux matrices verticalement, on utilise l\'instruction np.vstack,')
print('en plaçant les matrices entre parenthèses au sein des parenthèses de la fonction vstack :')
print(np.vstack( ( A[:,0:2] , B )),'\n')

print('Pour supprimer un élément d\'un vecteur, on utilise l\'instruction np.delete,')
print('en passant en second argument le numéro de l\'élement à supprimer')

V = np.array( [1,2,3] )
print('Voici le vecteur V')
print(V)
print('Voici le vecteur V où l\'on a enlevé l\'élément 2 :')
print(np.delete(V,1))

Voici la matrice A
[[1 2 0]
 [3 0 4]
 [0 5 6]]
Voici la matrice B
[[1 2]
 [3 4]
 [5 6]] 

On obtient ainsi la transposée de B : 
[[1 3 5]
 [2 4 6]] 

Par défaut, toute opération sur les matrices est réalisée terme à terme
Pour faire un produit matriciel, on utilise la méthode .dot()
[[ 7 10]
 [23 30]
 [45 56]] 

L'inverse d'une matrice carrée s'obtient comme suit. inv(A) est :
[[ 0.35714286  0.21428571 -0.14285714]
 [ 0.32142857 -0.10714286  0.07142857]
 [-0.26785714  0.08928571  0.10714286]] 

La pseudo-inverse d'une matrice rectangulaire s'obtient comme suit. pinv(B) est :
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]] 

Pour concaténer deux matrices horizontalement, on utilise l'instruction np.hstack,
en plaçant les matrices entre parenthèses au sein des parenthèses de la fonction hstack :
[[1 2 0 1 2]
 [3 0 4 3 4]
 [0 5 6 5 6]] 

Pour concaténer deux matrices verticalement, on utilise l'instruction np.vstack,
en plaçant les matrices entre parenthèses